import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type LangCode = 'en' | 'tl';

const LANG_KEY = 'dms_language';

const resources: Record<LangCode, any> = {
  en: {
    // ── Common / Shared ──
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    search: 'Search',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    na: 'N/A',
    ok: 'OK',
    done: 'Done',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    confirm: 'Confirm',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
    restore: 'Restore',
    approve: 'Approve',
    reject: 'Reject',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    all: 'All',
    none: 'None',
    department: 'Department',
    role: 'Role',
    date: 'Date',
    version: 'Version',
    description: 'Description',
    tags: 'Tags',
    fileType: 'File Type',
    fileSize: 'File Size',
    size: 'Size',
    viewDetails: 'View Details',
    current: 'Current',

    // ── Roles ──
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    administrator: 'Administrator',
    departmentManager: 'Department Manager',

    // ── Login Page ──
    documentManagementSystem: 'Document Management System',
    maptechCompany: 'Maptech Information Solution Inc.',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    emailAddress: 'Email Address',
    emailPlaceholder: 'your@maptech.com',
    password: 'Password',
    enterPassword: 'Enter your password',
    loginValidation: 'Please enter your email and password.',
    loginError: 'Invalid email or password. Please try again.',
    copyright: '© 2026 Maptech Information Solution Inc.',

    // ── Sidebar ──
    dashboard: 'Dashboard',
    pendingApprovals: 'Pending Approvals',
    documents: 'Documents',
    scannerDashboard: 'Scanner Dashboard',
    userManagement: 'User Management',
    deleteRequests: 'Delete Requests',
    archives: 'Archives',
    trash: 'Trash',
    activityLog: 'Activity Log',
    fullAccess: 'Full Access',
    logout: 'Logout',
    folderManagement: 'Folder Management',
    departmentManagement: 'Department Management',

    // ── Header ──
    searchDocuments: 'Search documents...',
    switchToLightMode: 'Switch to Light Mode',
    switchToDarkMode: 'Switch to Dark Mode',
    notifications: 'Notifications',
    unread: 'unread',
    noNotifications: 'No notifications',
    approvalNeeded: 'Approval Needed',
    needsApproval: 'needs approval',
    activityLogExport: 'Activity Log Export',
    deleteRequest: 'Delete Request',
    deleteApproved: 'Delete Approved',
    deleteDenied: 'Delete Denied',
    markAllRead: 'Mark all read',
    myProfile: 'My Profile',
    settings: 'Settings',
    signOut: 'Sign Out',
    maptechSubtitle: 'Maptech Information Solution Inc. — Document Management System',

    // ── Staff Dashboard ──
    welcome: 'Welcome, ',
    departmentSuffix: ' Department',
    uploadDocument: 'Upload Document',
    myDocuments: 'My Documents',
    documentsRejected: ' document(s) rejected',
    reviewRejection: 'Please review the rejection reasons and resubmit.',
    myRecentDocuments: 'My Recent Documents',
    viewAll: 'View all',
    noDocumentsYet: 'No documents yet',
    uploadFirstDocument: 'Upload your first document',
    addNewDocument: 'Add a new document',
    browseDocuments: 'Browse Documents',
    searchAndViewFiles: 'Search and view files',

    // ── Manager Dashboard ──
    managerDashboard: 'Manager Dashboard',
    reviewApproveDocs: 'Review and approve department documents',
    pendingApproval: 'Pending Approval',
    approvedByMe: 'Approved by Me',
    rejectedByMe: 'Rejected by Me',
    noDocsInCategory: 'No documents in this category',
    uploadedBy: 'Uploaded by ',
    reason: 'Reason: ',
    reasonForRejection: 'Reason for rejection:',
    explainRejection: 'Explain why this document is being rejected...',
    confirmRejection: 'Confirm Rejection',

    // ── Admin Dashboard ──
    adminDashboard: 'Admin Dashboard',
    adminDescription: 'Full system control — Maptech Information Solution Inc.',
    totalDocuments: 'Total Documents',
    totalFolders: 'Total Folders',
    inTrash: 'In Trash',

    // ── Documents Page ──
    folders: 'Folders',
    allDocuments: 'All Documents',
    searchByTitleOrRef: 'Search by title or reference...',
    allDepartments: 'All Departments',
    allStatus: 'All Status',
    allTypes: 'All Types',
    showing: 'Showing ',
    documentsLabel: ' documents',
    document: 'Document',
    noDocumentsFound: 'No documents found',
    createNewFolder: 'Create New Folder',
    folderName: 'Folder Name',
    enterFolderName: 'Enter folder name...',
    parentFolderOptional: 'Parent Folder (optional)',
    noneRootFolder: 'None (Root folder)',
    createFolder: 'Create Folder',
    needsApprovalLabel: 'Needs Approval',
    approvedByLabel: 'Approved By',
    encrypted: 'Encrypted',
    rejectionReason: 'Rejection Reason:',
    moveToTrash: 'Move to Trash',
    restoreFromTrash: 'You can restore it from the Trash page.',
    failedToDownload: 'Failed to download file.',
    deleteApprovalRequested: 'Delete approval requested',
    failedToDeleteFolder: 'Failed to delete folder',

    // ── Archive Page ──
    documentArchives: 'Document Archives',
    archivedDocuments: ' archived documents',
    searchArchived: 'Search archived documents...',
    noArchivedDocuments: 'No archived documents',
    archivedDocsAppearHere: 'Documents moved to archive will appear here',
    archived: 'Archived',
    retention: 'Retention',
    daysAgo: ' days ago',
    expired: 'Expired',
    dRemaining: 'd remaining',
    permanentDeleteConfirm: 'This cannot be undone.',

    // ── Trash Page ──
    trashTitle: 'Trash',
    trashDescription: 'Documents are permanently deleted after 30 days',
    emptyTrash: 'Empty Trash',
    documentsInTrash: ' document(s) in trash',
    trashAutoDelete: 'Documents are automatically deleted after 30 days. Restore them before they expire.',
    searchTrash: 'Search trash...',
    trashIsEmpty: 'Trash is empty',
    deletedDocsAppearHere: 'Deleted documents will appear here for 30 days',
    deletedBy: 'Deleted By',
    expiresIn: 'Expires In',
    expiresToday: 'Expires today',
    days: ' days',
    confirmDelete: 'Confirm Delete',
    emptyTrashConfirm: 'Empty trash? All documents will be permanently deleted.',

    // ── Folder Management ──
    folderManagementTitle: 'Folder Management',
    organizeControlFolders: 'Organize and control document folders',
    newFolder: 'New Folder',
    folderStructure: 'Folder Structure',
    hoverFolderActions: 'Hover over a folder to see actions',
    createSubfolder: 'Create Subfolder',
    createRootFolder: 'Create Root Folder',
    under: 'Under: ',
    folderNameRequired: 'Folder Name *',
    folderNamePlaceholder: 'e.g. Q1 Reports',
    folderPermissions: 'Folder Permissions',
    fullAccessPerm: 'Full access',
    readWritePerm: 'Read/Write',
    readOnlyPerm: 'Read only',
    savePermissions: 'Save Permissions',
    folderNameRequiredMsg: 'Folder name is required.',

    // ── Staff Folder Dashboard ──
    myFolders: 'My Folders',
    createManagePrivateFolders: 'Create and manage your private folders',
    onlyAccessibleFolders: 'Only folders you can access are shown',
    folderNameRequiredAlert: 'Folder name required',

    // ── Scanner Dashboard ──
    scannerDashboardTitle: 'Scanner Dashboard',
    realScanReady: 'Real scan integration ready',
    refresh: 'Refresh',
    connectedDevices: 'Connected Devices',
    noScannersConnected: 'No scanners connected.',
    scanSettings: 'Scan Settings',
    documentTitleRequired: 'Document Title *',
    format: 'Format',
    destinationFolder: 'Destination Folder',
    scanComplete: 'Scan complete! Document added.',
    processing: 'Processing...',
    startScan: 'Start Scan',
    recentScans: 'Recent Scans',
    enterDocumentTitle: 'Please enter a document title.',

    // ── User Management ──
    manageUsersAndDepts: 'Manage system users and departments',
    addUser: 'Add User',
    users: 'Users',
    departments: 'Departments',
    searchUsers: 'Search users...',
    user: 'User',
    created: 'Created',
    addDepartment: 'Add Department',
    staffCount: ' staff',
    docsCount: ' docs',
    addNewUser: 'Add New User',
    createNewAccount: 'Create a new system account',
    fullName: 'Full Name',
    fullNameRequired: 'Full Name *',
    emailRequired: 'Email Address *',
    passwordRequired: 'Password *',
    johnDoe: 'John Doe',
    johnEmail: 'john@maptech.com',
    minSixChars: 'Min. 6 characters',
    selectDepartment: 'Select department...',
    createUser: 'Create User',
    addNewDepartment: 'Add New Department',
    departmentNameRequired: 'Department Name *',
    egOperations: 'e.g. Operations',
    createDepartment: 'Create Department',
    deleteUser: 'Delete User',
    deleteUserConfirm: 'Are you sure you want to delete',
    deleteUserWarning: 'All folders and documents created by this user will be permanently deleted.',
    deleteDepartment: 'Delete Department',
    deleteDeptWarning: 'All folders and documents under this department will be permanently deleted.',
    resetPassword: 'Reset Password',
    enterNewPasswordFor: 'Enter a new password for',
    newPasswordPlaceholder: 'New password (min. 6 characters)',
    passwordUpdated: 'Password Updated',
    passwordResetSuccess: 'has been reset successfully.',
    passwordMinChars: 'Password must be at least 6 characters.',
    failedResetPassword: 'Failed to reset password. Please try again.',
    fillRequiredFields: 'Please fill in all required fields including department.',
    departmentNameRequiredMsg: 'Department name is required.',
    deactivate: 'Deactivate',
    activate: 'Activate',

    // ── Department Management ──
    manageCompanyDepts: 'Manage company departments',
    searchDepartments: 'Search departments...',
    members: ' member(s)',
    departmentManagerLabel: 'Department Manager',
    noDepartmentsFound: 'No departments found',
    enterDepartmentName: 'Enter department name',
    cannotDeleteDept: 'Cannot delete',
    hasUsersAssigned: 'because it has',
    usersAssignedSuffix: 'user(s) assigned. Please reassign users first.',
    confirmDeleteDept: 'Are you sure you want to delete',

    // ── Activity Log ──
    activityLogTitle: 'Activity Log',
    completeAuditTrail: 'Complete audit trail — ',
    entries: ' entries',
    export: 'Export',
    exportExcel: 'Export as Excel',
    exportPdf: 'Export as PDF',
    searchActivityLog: 'Search by user, action, or target...',
    allActions: 'All Actions',
    uploads: 'Uploads',
    approvals: 'Approvals',
    rejections: 'Rejections',
    downloads: 'Downloads',
    archivesAction: 'Archives',
    deletions: 'Deletions',
    logins: 'Logins',
    logouts: 'Logouts',
    userUpdates: 'User Updates',
    allRoles: 'All Roles',
    showingOf: 'Showing ',
    of: ' of ',
    entriesLabel: ' entries',
    timestamp: 'Timestamp',
    action: 'Action',
    target: 'Target',
    ipAddress: 'IP Address',
    details: 'Details',
    noLogEntries: 'No log entries found',

    // ── Admin Delete Requests ──
    deleteRequestsTitle: 'Delete Requests',
    reviewManageDeletions: 'Review and manage deletion requests from staff',
    pendingReview: 'Pending review',
    requestedBy: 'Requested by ',
    requestsAppearHere: 'Requests will appear here when staff submit them',
    loadingRequests: 'Loading requests...',
    noRequests: 'No',
    requests: 'requests',

    // ── Profile Page ──
    profileDetails: 'Profile Details',
    enterFullName: 'Enter your full name',
    nameAtCompany: 'name@company.com',
    contactAdminDept: 'Contact admin to change department',
    rolesCannotChange: 'Roles cannot be changed by user',
    memberSince: 'Member since',
    profilePhotoUpdated: 'Profile photo updated',
    profileUpdated: 'Profile updated successfully',
    fillAllPasswordFields: 'Please fill all password fields',
    passwordMinSixChars: 'New password must be at least 6 characters',
    passwordMismatch: 'New password and confirm password do not match',
    failedChangePassword: 'Failed to change password — check current password',
    networkErrorPassword: 'Network error — could not change password',

    // ── Settings Page ──
    settingsDescription: 'Manage your application preferences and configuration',
    regional: 'Regional',
    language: 'Language',
    timezone: 'Timezone',
    appearance: 'Appearance',
    notificationsDescription: 'Choose how you want to be notified',
    emailNotificationsTitle: 'Email Notifications',
    emailNotificationsDesc: 'Receive daily summaries and important alerts',
    browserNotificationsTitle: 'Browser Notifications',
    browserNotificationsDesc: 'Show popup notifications when online',
    approvalRequestsTitle: 'Approval Requests',
    approvalRequestsDesc: 'Notify me when documents need approval',
    appearanceDescription: 'Customize how the application looks',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    system: 'System',
    security: 'Security',
    securityDesc: 'Change your password',
    activeSessions: 'Active Sessions',
    manageActiveSessions: 'Manage your active sessions',
    revoke: 'Revoke',
    savePreferences: 'Save Preferences',
    updatePassword: 'Update Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordChangedMsg: 'Password changed — you will be logged out',
    logoSettings: 'Logo Settings',
    logoSettingsDesc: 'Change the logo',

    // ── Upload Modal ──
    documentUploaded: 'Document Uploaded!',
    submittedForApproval: 'Your document has been submitted for approval.',
    savedSuccessfully: 'Your document has been saved successfully.',
    reference: 'Reference: ',
    uploadNewDocument: 'Upload New Document',
    fillDocDetails: 'Fill in document details and attach a file',
    dragDropFile: 'Drag & drop your file here',
    supportedFormats: 'PDF, DOC, DOCX, XLSX, JPG, PNG, TIFF and video files supported',
    browseFiles: 'Browse Files',
    documentTitleLabel: 'Document Title *',
    egQ1Report: 'e.g. Q1 Financial Report',
    referenceNumber: 'Reference Number',
    generatedAfterUpload: 'Will be generated after upload',
    saveToFolder: 'Save to Folder',
    rootFolders: 'Root Folders',
    subfolders: 'Subfolders',
    briefDescription: 'Brief description of this document...',
    tagsCommaSeparated: 'Tags (comma-separated)',
    egTags: 'e.g. financial, quarterly, 2026',
    requiresApproval: 'Requires Approval',
    sentToManagerReview: 'This document will be sent to manager for review',
    uploading: 'Uploading...',
    submitForApproval: 'Submit for Approval',
    titleRequired: 'Title is required',
    pleaseAttachFile: 'Please attach a file',
    selectFolderBeforeUpload: 'Please select a folder before uploading.',
    uploadFailed: 'Upload failed',
    duplicateReference: 'Duplicate reference generated — please try again',
    networkErrorUpload: 'Network error — upload failed',

    // ── Scan Modal ──
    scanDocument: 'Scan Document',
    scannerConnected: 'Scanner connected and ready',
    optionalAutoGenerated: 'Optional - auto-generated if empty',
    resolution: 'Resolution',
    colorMode: 'Color Mode',
    color: 'Color',
    grayscale: 'Grayscale',
    blackAndWhite: 'Black & White',
    alsoSendToEmail: 'Also send to email',
    enterEmailAddress: 'Enter email address',
    startScanning: 'Start Scanning',
    scanningDocument: 'Scanning document...',
    pleaseWaitScanning: 'Please wait while the document is being scanned',
    scanCompleteTitle: 'Scan Complete!',
    documentSavedSuccessfully: 'Document has been saved successfully',
    scanFailed: 'Scan Failed',
    checkScannerConnection: 'Please check the scanner connection and try again',
    tryAgain: 'Try Again',

    // ── Approval Modal ──
    reviewDocument: 'Review Document',
    unknown: 'Unknown',
    rejectionReasonRequired: 'Rejection Reason *',
    provideRejectionReason: 'Please provide a reason for rejection...',

    // ── Delete / Request Delete Modals ──
    deleteFolder: 'Delete Folder',
    cannotDeleteFolderSubs: 'it has',
    subfoldersSuffix: 'subfolder(s). Delete subfolders first.',
    confirmDeleteFolder: 'Are you sure you want to delete',
    actionCannotBeUndone: 'This action cannot be undone.',
    requestDocumentDeletion: 'Request Document Deletion',
    requestDeleteDesc: 'This will send a request to the admin for approval. The document will not be deleted until approved.',
    reasonForDeletion: 'Reason for deletion (optional)',
    deleteRequestSuccess: 'Delete request sent successfully!',
    requesting: 'Requesting...',
    requestDelete: 'Request Delete',
    failedRequestDelete: 'Failed to request delete',

    // ── Create User Modal ──
    createNewUser: 'Create New User',
    enterFullNamePlaceholder: 'Enter full name',
    enterEmailPlaceholder: 'Enter email address',
    roleRequired: 'Role *',
    departmentRequired: 'Department *',
    selectDepartmentOption: 'Select department',
    enterPasswordPlaceholder: 'Enter password (min 6 characters)',
    confirmPasswordRequired: 'Confirm Password *',
    confirmPasswordPlaceholder: 'Confirm password',
    emailMustEndWith: 'Email address must end with @maptech.com',
    passwordsDoNotMatch: 'Passwords do not match',
    failedCreateUser: 'Failed to create user.',

    // ── Create Folder Modal ──
    parentFolder: 'Parent Folder',
    rootNoParent: 'Root (No parent)',
    unassigned: 'Unassigned',
    visibility: 'Visibility',
    adminOnly: 'Admin Only',
    private: 'Private',

    // ── Document Card ──
    review: 'Review',
    archive: 'Archive',
    requestDeleteOption: 'Request Delete',
    by: 'by ',

    // ── File Preview ──
    noDocumentSelected: 'No document selected.',
    previewNotAvailableFor: 'Preview not available for',
    files: 'files.',
    loadingPreview: 'Loading preview...',
    browserNoVideo: 'Your browser does not support video playback.',
    downloadToPreview: 'Download to Preview',
    downloadFile: 'Download File',
    previewNotAvailable: 'Preview not available.',

    // ── Folder Tree ──
    searchFolders: 'Search folders...',

    // ── Activity Log Export Popup ──
    activityLogAlert: 'Activity Log Alert',
    activityLogsReached: 'Activity logs reached',
    records: 'records.',
    downloadExcelReport: 'Please download the Excel report.',
    exportedLogsArchived: 'The exported logs will be moved to the archive after downloading.',
    dismiss: 'Dismiss',
    downloading: 'Downloading...',
    pdf: 'PDF',
    excel: 'Excel',

    // ── Page Titles (used in Header) ──
    pageTitles: {
      dashboard: 'Dashboard',
      documents: 'Document Management',
      scanner: 'Scanner Dashboard',
      users: 'User Management',
      folders: 'Folder Management',
      departments: 'Department Management',
      archive: 'Archives',
      trash: 'Trash',
      'activity-log': 'Activity Log',
      approvals: 'Pending Approvals',
      'admin-delete-requests': 'Delete Request',
      profile: 'My Profile',
      settings: 'Settings'
    }
  },

  tl: {
    // ── Common / Shared ──
    cancel: 'Kanselahin',
    close: 'Isara',
    save: 'I-save',
    delete: 'Tanggalin',
    edit: 'I-edit',
    create: 'Gumawa',
    search: 'Maghanap',
    actions: 'Aksyon',
    status: 'Katayuan',
    active: 'Aktibo',
    inactive: 'Hindi aktibo',
    yes: 'Oo',
    no: 'Hindi',
    na: 'N/A',
    ok: 'OK',
    done: 'Tapos na',
    loading: 'Naglo-load...',
    error: 'Error',
    success: 'Tagumpay',
    warning: 'Babala',
    confirm: 'Kumpirmahin',
    view: 'Tingnan',
    download: 'I-download',
    upload: 'I-upload',
    restore: 'Ibalik',
    approve: 'Aprubahan',
    reject: 'Tanggihan',
    pending: 'Pending',
    approved: 'Naaprubahan',
    rejected: 'Tinanggihan',
    all: 'Lahat',
    none: 'Wala',
    department: 'Departamento',
    role: 'Tungkulin',
    date: 'Petsa',
    version: 'Bersyon',
    description: 'Paglalarawan',
    tags: 'Mga Tag',
    fileType: 'Uri ng File',
    fileSize: 'Laki ng File',
    size: 'Laki',
    viewDetails: 'Tingnan ang Detalye',
    current: 'Kasalukuyan',

    // ── Roles ──
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    administrator: 'Tagapangasiwa',
    departmentManager: 'Tagapamahala ng Departamento',

    // ── Login Page ──
    documentManagementSystem: 'Sistema ng Pamamahala ng Dokumento',
    maptechCompany: 'Maptech Information Solution Inc.',
    signIn: 'Mag-sign In',
    signingIn: 'Nagsa-sign in...',
    emailAddress: 'Email Address',
    emailPlaceholder: 'your@maptech.com',
    password: 'Password',
    enterPassword: 'Ilagay ang iyong password',
    loginValidation: 'Mangyaring ilagay ang iyong email at password.',
    loginError: 'Hindi wastong email o password. Pakisubukang muli.',
    copyright: '© 2026 Maptech Information Solution Inc.',

    // ── Sidebar ──
    dashboard: 'Dashboard',
    pendingApprovals: 'Mga Pending na Pag-apruba',
    documents: 'Mga Dokumento',
    scannerDashboard: 'Scanner Dashboard',
    userManagement: 'Pamamahala ng User',
    deleteRequests: 'Mga Kahilingan ng Pagtanggal',
    archives: 'Archive',
    trash: 'Trash',
    activityLog: 'Activity Log',
    fullAccess: 'Buong Access',
    logout: 'Mag-logout',
    folderManagement: 'Pamamahala ng Folder',
    departmentManagement: 'Pamamahala ng Departamento',

    // ── Header ──
    searchDocuments: 'Maghanap ng mga dokumento...',
    switchToLightMode: 'Lumipat sa Light Mode',
    switchToDarkMode: 'Lumipat sa Dark Mode',
    notifications: 'Mga Abiso',
    unread: 'hindi nabasa',
    noNotifications: 'Walang abiso',
    approvalNeeded: 'Kailangan ng Pag-apruba',
    needsApproval: 'kailangan ng pag-apruba',
    activityLogExport: 'I-export ang Activity Log',
    deleteRequest: 'Kahilingan ng Pagtanggal',
    deleteApproved: 'Naaprubahang Pagtanggal',
    deleteDenied: 'Tinanggihang Pagtanggal',
    markAllRead: 'Markahang lahat na nabasa',
    myProfile: 'Aking Profile',
    settings: 'Mga Setting',
    signOut: 'Mag-sign Out',
    maptechSubtitle: 'Maptech Information Solution Inc. — Sistema ng Pamamahala ng Dokumento',

    // ── Staff Dashboard ──
    welcome: 'Maligayang pagdating, ',
    departmentSuffix: ' na Departamento',
    uploadDocument: 'Mag-upload ng Dokumento',
    myDocuments: 'Aking mga Dokumento',
    documentsRejected: ' dokumento ang tinanggihan',
    reviewRejection: 'Mangyaring suriin ang mga dahilan ng pagtanggi at muling isumite.',
    myRecentDocuments: 'Aking Kamakailang mga Dokumento',
    viewAll: 'Tingnan lahat',
    noDocumentsYet: 'Wala pang mga dokumento',
    uploadFirstDocument: 'I-upload ang iyong unang dokumento',
    addNewDocument: 'Magdagdag ng bagong dokumento',
    browseDocuments: 'Mag-browse ng mga Dokumento',
    searchAndViewFiles: 'Maghanap at tingnan ang mga file',

    // ── Manager Dashboard ──
    managerDashboard: 'Dashboard ng Manager',
    reviewApproveDocs: 'Suriin at aprubahan ang mga dokumento ng departamento',
    pendingApproval: 'Pending na Pag-apruba',
    approvedByMe: 'Inaaprubahan Ko',
    rejectedByMe: 'Tinanggihan Ko',
    noDocsInCategory: 'Walang dokumento sa kategoryang ito',
    uploadedBy: 'In-upload ni ',
    reason: 'Dahilan: ',
    reasonForRejection: 'Dahilan ng pagtanggi:',
    explainRejection: 'Ipaliwanag kung bakit tinatanggihan ang dokumentong ito...',
    confirmRejection: 'Kumpirmahin ang Pagtanggi',

    // ── Admin Dashboard ──
    adminDashboard: 'Dashboard ng Admin',
    adminDescription: 'Buong kontrol ng sistema — Maptech Information Solution Inc.',
    totalDocuments: 'Kabuuang mga Dokumento',
    totalFolders: 'Kabuuang mga Folder',
    inTrash: 'Sa Trash',

    // ── Documents Page ──
    folders: 'Mga Folder',
    allDocuments: 'Lahat ng Dokumento',
    searchByTitleOrRef: 'Maghanap ayon sa pamagat o reference...',
    allDepartments: 'Lahat ng Departamento',
    allStatus: 'Lahat ng Katayuan',
    allTypes: 'Lahat ng Uri',
    showing: 'Nagpapakita ng ',
    documentsLabel: ' mga dokumento',
    document: 'Dokumento',
    noDocumentsFound: 'Walang nahanap na dokumento',
    createNewFolder: 'Gumawa ng Bagong Folder',
    folderName: 'Pangalan ng Folder',
    enterFolderName: 'Ilagay ang pangalan ng folder...',
    parentFolderOptional: 'Parent Folder (opsyonal)',
    noneRootFolder: 'Wala (Root folder)',
    createFolder: 'Gumawa ng Folder',
    needsApprovalLabel: 'Kailangan ng Pag-apruba',
    approvedByLabel: 'Inaaprubahan Ni',
    encrypted: 'Naka-encrypt',
    rejectionReason: 'Dahilan ng Pagtanggi:',
    moveToTrash: 'Ilipat sa Trash',
    restoreFromTrash: 'Maaari mong ibalik ito mula sa pahina ng Trash.',
    failedToDownload: 'Hindi na-download ang file.',
    deleteApprovalRequested: 'Naisumite na ang kahilingan ng pagtanggal',
    failedToDeleteFolder: 'Hindi natanggal ang folder',

    // ── Archive Page ──
    documentArchives: 'Archive ng mga Dokumento',
    archivedDocuments: ' naka-archive na dokumento',
    searchArchived: 'Maghanap ng naka-archive na dokumento...',
    noArchivedDocuments: 'Walang naka-archive na dokumento',
    archivedDocsAppearHere: 'Ang mga dokumentong inilipat sa archive ay lalabas dito',
    archived: 'Na-archive',
    retention: 'Pagpapanatili',
    daysAgo: ' araw ang nakalipas',
    expired: 'Nag-expire na',
    dRemaining: 'd natitira',
    permanentDeleteConfirm: 'Hindi na ito maibabalik.',

    // ── Trash Page ──
    trashTitle: 'Trash',
    trashDescription: 'Ang mga dokumento ay permanenteng tatanggalin pagkatapos ng 30 araw',
    emptyTrash: 'I-empty ang Trash',
    documentsInTrash: ' dokumento sa trash',
    trashAutoDelete: 'Ang mga dokumento ay awtomatikong tatanggalin pagkatapos ng 30 araw. Ibalik sila bago mag-expire.',
    searchTrash: 'Maghanap sa trash...',
    trashIsEmpty: 'Walang laman ang Trash',
    deletedDocsAppearHere: 'Ang mga tinanggal na dokumento ay lalabas dito sa loob ng 30 araw',
    deletedBy: 'Tinanggal Ni',
    expiresIn: 'Mag-e-expire Sa',
    expiresToday: 'Mag-e-expire ngayon',
    days: ' araw',
    confirmDelete: 'Kumpirmahin ang Pagtanggal',
    emptyTrashConfirm: 'I-empty ang trash? Lahat ng dokumento ay permanenteng tatanggalin.',

    // ── Folder Management ──
    folderManagementTitle: 'Pamamahala ng Folder',
    organizeControlFolders: 'Ayusin at kontrolin ang mga folder ng dokumento',
    newFolder: 'Bagong Folder',
    folderStructure: 'Istraktura ng Folder',
    hoverFolderActions: 'I-hover ang isang folder para makita ang mga aksyon',
    createSubfolder: 'Gumawa ng Subfolder',
    createRootFolder: 'Gumawa ng Root Folder',
    under: 'Sa ilalim ng: ',
    folderNameRequired: 'Pangalan ng Folder *',
    folderNamePlaceholder: 'hal. Q1 Reports',
    folderPermissions: 'Mga Pahintulot ng Folder',
    fullAccessPerm: 'Buong access',
    readWritePerm: 'Basa/Sulat',
    readOnlyPerm: 'Basa lamang',
    savePermissions: 'I-save ang mga Pahintulot',
    folderNameRequiredMsg: 'Kailangan ang pangalan ng folder.',

    // ── Staff Folder Dashboard ──
    myFolders: 'Aking mga Folder',
    createManagePrivateFolders: 'Gumawa at pamahalaan ang iyong mga pribadong folder',
    onlyAccessibleFolders: 'Mga folder na maa-access mo lang ang ipinapakita',
    folderNameRequiredAlert: 'Kailangan ang pangalan ng folder',

    // ── Scanner Dashboard ──
    scannerDashboardTitle: 'Scanner Dashboard',
    realScanReady: 'Handa na ang pag-scan',
    refresh: 'I-refresh',
    connectedDevices: 'Mga Nakakonektang Device',
    noScannersConnected: 'Walang nakakonektang scanner.',
    scanSettings: 'Mga Setting ng Scan',
    documentTitleRequired: 'Pamagat ng Dokumento *',
    format: 'Format',
    destinationFolder: 'Destinasyong Folder',
    scanComplete: 'Tapos na ang scan! Naidagdag ang dokumento.',
    processing: 'Pinoproseso...',
    startScan: 'Simulan ang Scan',
    recentScans: 'Kamakailang mga Scan',
    enterDocumentTitle: 'Mangyaring maglagay ng pamagat ng dokumento.',

    // ── User Management ──
    manageUsersAndDepts: 'Pamahalaan ang mga user at departamento ng sistema',
    addUser: 'Magdagdag ng User',
    users: 'Mga User',
    departments: 'Mga Departamento',
    searchUsers: 'Maghanap ng mga user...',
    user: 'User',
    created: 'Ginawa',
    addDepartment: 'Magdagdag ng Departamento',
    staffCount: ' staff',
    docsCount: ' docs',
    addNewUser: 'Magdagdag ng Bagong User',
    createNewAccount: 'Gumawa ng bagong account sa sistema',
    fullName: 'Buong Pangalan',
    fullNameRequired: 'Buong Pangalan *',
    emailRequired: 'Email Address *',
    passwordRequired: 'Password *',
    johnDoe: 'Juan dela Cruz',
    johnEmail: 'juan@maptech.com',
    minSixChars: 'Min. 6 na letra',
    selectDepartment: 'Pumili ng departamento...',
    createUser: 'Gumawa ng User',
    addNewDepartment: 'Magdagdag ng Bagong Departamento',
    departmentNameRequired: 'Pangalan ng Departamento *',
    egOperations: 'hal. Operations',
    createDepartment: 'Gumawa ng Departamento',
    deleteUser: 'Tanggalin ang User',
    deleteUserConfirm: 'Sigurado ka bang gusto mong tanggalin si',
    deleteUserWarning: 'Lahat ng folder at dokumento na ginawa ng user na ito ay permanenteng tatanggalin.',
    deleteDepartment: 'Tanggalin ang Departamento',
    deleteDeptWarning: 'Lahat ng folder at dokumento sa ilalim ng departamentong ito ay permanenteng tatanggalin.',
    resetPassword: 'I-reset ang Password',
    enterNewPasswordFor: 'Maglagay ng bagong password para kay',
    newPasswordPlaceholder: 'Bagong password (min. 6 na letra)',
    passwordUpdated: 'Na-update na ang Password',
    passwordResetSuccess: 'ay matagumpay na na-reset.',
    passwordMinChars: 'Ang password ay dapat hindi bababa sa 6 na letra.',
    failedResetPassword: 'Hindi ma-reset ang password. Pakisubukang muli.',
    fillRequiredFields: 'Mangyaring punan ang lahat ng kinakailangang field kasama ang departamento.',
    departmentNameRequiredMsg: 'Kailangan ang pangalan ng departamento.',
    deactivate: 'I-deactivate',
    activate: 'I-activate',

    // ── Department Management ──
    manageCompanyDepts: 'Pamahalaan ang mga departamento ng kumpanya',
    searchDepartments: 'Maghanap ng mga departamento...',
    members: ' miyembro',
    departmentManagerLabel: 'Tagapamahala ng Departamento',
    noDepartmentsFound: 'Walang nahanap na departamento',
    enterDepartmentName: 'Ilagay ang pangalan ng departamento',
    cannotDeleteDept: 'Hindi matanggal ang',
    hasUsersAssigned: 'dahil mayroon itong',
    usersAssignedSuffix: 'user na naka-assign. Mangyaring i-reassign muna ang mga user.',
    confirmDeleteDept: 'Sigurado ka bang gusto mong tanggalin ang',

    // ── Activity Log ──
    activityLogTitle: 'Activity Log',
    completeAuditTrail: 'Kumpletong audit trail — ',
    entries: ' mga entry',
    export: 'I-export',
    exportExcel: 'I-export bilang Excel',
    exportPdf: 'I-export bilang PDF',
    searchActivityLog: 'Maghanap sa user, aksyon, o target...',
    allActions: 'Lahat ng Aksyon',
    uploads: 'Mga Upload',
    approvals: 'Mga Pag-apruba',
    rejections: 'Mga Pagtanggi',
    downloads: 'Mga Download',
    archivesAction: 'Mga Archive',
    deletions: 'Mga Pagtanggal',
    logins: 'Mga Login',
    logouts: 'Mga Logout',
    userUpdates: 'Mga Update ng User',
    allRoles: 'Lahat ng Tungkulin',
    showingOf: 'Nagpapakita ng ',
    of: ' sa ',
    entriesLabel: ' mga entry',
    timestamp: 'Oras',
    action: 'Aksyon',
    target: 'Target',
    ipAddress: 'IP Address',
    details: 'Mga Detalye',
    noLogEntries: 'Walang nahanap na log entry',

    // ── Admin Delete Requests ──
    deleteRequestsTitle: 'Mga Kahilingan ng Pagtanggal',
    reviewManageDeletions: 'Suriin at pamahalaan ang mga kahilingan ng pagtanggal mula sa staff',
    pendingReview: 'Pending na pagsusuri',
    requestedBy: 'Hiniling ni ',
    requestsAppearHere: 'Ang mga kahilingan ay lalabas dito kapag naisumite ng staff',
    loadingRequests: 'Naglo-load ng mga kahilingan...',
    noRequests: 'Walang',
    requests: 'mga kahilingan',

    // ── Profile Page ──
    profileDetails: 'Mga Detalye ng Profile',
    enterFullName: 'Ilagay ang iyong buong pangalan',
    nameAtCompany: 'pangalan@kumpanya.com',
    contactAdminDept: 'Kontakin ang admin para baguhin ang departamento',
    rolesCannotChange: 'Hindi mababago ng user ang mga tungkulin',
    memberSince: 'Miyembro mula noong',
    profilePhotoUpdated: 'Na-update na ang litratong pang-profile',
    profileUpdated: 'Matagumpay na na-update ang profile',
    fillAllPasswordFields: 'Mangyaring punan ang lahat ng field ng password',
    passwordMinSixChars: 'Ang bagong password ay dapat hindi bababa sa 6 na letra',
    passwordMismatch: 'Hindi magkatugma ang bagong password at kumpirmasyon ng password',
    failedChangePassword: 'Hindi nabago ang password — suriin ang kasalukuyang password',
    networkErrorPassword: 'Network error — hindi nabago ang password',

    // ── Settings Page ──
    settingsDescription: 'Pamahalaan ang iyong mga kagustuhan at pagsasaayos ng aplikasyon',
    regional: 'Rehiyon',
    language: 'Wika',
    timezone: 'Time Zone',
    appearance: 'Hitsura',
    notificationsDescription: 'Piliin kung paano ka nais abisuhan',
    emailNotificationsTitle: 'Mga Email na Abiso',
    emailNotificationsDesc: 'Tanggapin ang pang-araw-araw na buod at mahahalagang abiso',
    browserNotificationsTitle: 'Browser na Abiso',
    browserNotificationsDesc: 'Ipakita ang popup na abiso kapag online',
    approvalRequestsTitle: 'Mga Request para sa Pag-apruba',
    approvalRequestsDesc: 'Abisuhan ako kapag ang mga dokumento ay nangangailangan ng pag-apruba',
    appearanceDescription: 'I-customize kung paano lumilitaw ang aplikasyon',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    system: 'System',
    security: 'Seguridad',
    securityDesc: 'Palitan ang iyong password',
    activeSessions: 'Aktibong Sesyon',
    manageActiveSessions: 'Pamahalaan ang iyong mga aktibong sesyon',
    revoke: 'I-revoke',
    savePreferences: 'I-save ang Mga Setting',
    updatePassword: 'I-update ang Password',
    currentPassword: 'Kasalukuyang Password',
    newPassword: 'Bagong Password',
    confirmNewPassword: 'Kumpirmahin ang Bagong Password',
    passwordChangedMsg: 'Nabago ang password — magla-logout ang system',
    logoSettings: 'Mga Setting ng Logo',
    logoSettingsDesc: 'Baguhin ang logo',

    // ── Upload Modal ──
    documentUploaded: 'Na-upload na ang Dokumento!',
    submittedForApproval: 'Ang iyong dokumento ay isinumite na para sa pag-apruba.',
    savedSuccessfully: 'Ang iyong dokumento ay matagumpay na na-save.',
    reference: 'Reference: ',
    uploadNewDocument: 'Mag-upload ng Bagong Dokumento',
    fillDocDetails: 'Punan ang mga detalye ng dokumento at mag-attach ng file',
    dragDropFile: 'I-drag at i-drop ang iyong file dito',
    supportedFormats: 'PDF, DOC, DOCX, XLSX, JPG, PNG, TIFF at mga video file ang suportado',
    browseFiles: 'Mag-browse ng mga File',
    documentTitleLabel: 'Pamagat ng Dokumento *',
    egQ1Report: 'hal. Q1 Financial Report',
    referenceNumber: 'Numerong Sanggunian',
    generatedAfterUpload: 'Magagawa pagkatapos mag-upload',
    saveToFolder: 'I-save sa Folder',
    rootFolders: 'Mga Root Folder',
    subfolders: 'Mga Subfolder',
    briefDescription: 'Maikling paglalarawan ng dokumentong ito...',
    tagsCommaSeparated: 'Mga Tag (pinaghihiwalay ng kuwit)',
    egTags: 'hal. pinansyal, quarterly, 2026',
    requiresApproval: 'Kailangan ng Pag-apruba',
    sentToManagerReview: 'Ang dokumentong ito ay ipapadala sa manager para sa pagsusuri',
    uploading: 'Nag-a-upload...',
    submitForApproval: 'Isumite para sa Pag-apruba',
    titleRequired: 'Kailangan ang pamagat',
    pleaseAttachFile: 'Mangyaring mag-attach ng file',
    selectFolderBeforeUpload: 'Mangyaring pumili ng folder bago mag-upload.',
    uploadFailed: 'Hindi na-upload',
    duplicateReference: 'Duplicate na reference — pakisubukang muli',
    networkErrorUpload: 'Network error — hindi na-upload',

    // ── Scan Modal ──
    scanDocument: 'Mag-scan ng Dokumento',
    scannerConnected: 'Nakakonekta at handa na ang scanner',
    optionalAutoGenerated: 'Opsyonal - awtomatikong gagawin kung walang laman',
    resolution: 'Resolution',
    colorMode: 'Color Mode',
    color: 'Kulay',
    grayscale: 'Grayscale',
    blackAndWhite: 'Itim at Puti',
    alsoSendToEmail: 'Ipadala rin sa email',
    enterEmailAddress: 'Ilagay ang email address',
    startScanning: 'Simulan ang Pag-scan',
    scanningDocument: 'Nag-i-scan ng dokumento...',
    pleaseWaitScanning: 'Mangyaring maghintay habang ini-scan ang dokumento',
    scanCompleteTitle: 'Tapos na ang Scan!',
    documentSavedSuccessfully: 'Matagumpay na na-save ang dokumento',
    scanFailed: 'Hindi Na-scan',
    checkScannerConnection: 'Mangyaring suriin ang koneksyon ng scanner at subukang muli',
    tryAgain: 'Subukang Muli',

    // ── Approval Modal ──
    reviewDocument: 'Suriin ang Dokumento',
    unknown: 'Hindi alam',
    rejectionReasonRequired: 'Dahilan ng Pagtanggi *',
    provideRejectionReason: 'Mangyaring magbigay ng dahilan ng pagtanggi...',

    // ── Delete / Request Delete Modals ──
    deleteFolder: 'Tanggalin ang Folder',
    cannotDeleteFolderSubs: 'mayroon itong',
    subfoldersSuffix: 'subfolder. Tanggalin muna ang mga subfolder.',
    confirmDeleteFolder: 'Sigurado ka bang gusto mong tanggalin ang',
    actionCannotBeUndone: 'Hindi na maibabalik ang aksyong ito.',
    requestDocumentDeletion: 'Humiling ng Pagtanggal ng Dokumento',
    requestDeleteDesc: 'Ito ay magpapadala ng kahilingan sa admin para sa pag-apruba. Hindi tatanggalin ang dokumento hangga\'t hindi naaprubahan.',
    reasonForDeletion: 'Dahilan ng pagtanggal (opsyonal)',
    deleteRequestSuccess: 'Matagumpay na naipadala ang kahilingan ng pagtanggal!',
    requesting: 'Hinihiling...',
    requestDelete: 'Humiling ng Pagtanggal',
    failedRequestDelete: 'Hindi naipadala ang kahilingan ng pagtanggal',

    // ── Create User Modal ──
    createNewUser: 'Gumawa ng Bagong User',
    enterFullNamePlaceholder: 'Ilagay ang buong pangalan',
    enterEmailPlaceholder: 'Ilagay ang email address',
    roleRequired: 'Tungkulin *',
    departmentRequired: 'Departamento *',
    selectDepartmentOption: 'Pumili ng departamento',
    enterPasswordPlaceholder: 'Ilagay ang password (min 6 na letra)',
    confirmPasswordRequired: 'Kumpirmahin ang Password *',
    confirmPasswordPlaceholder: 'Kumpirmahin ang password',
    emailMustEndWith: 'Ang email address ay dapat magtapos sa @maptech.com',
    passwordsDoNotMatch: 'Hindi magkatugma ang mga password',
    failedCreateUser: 'Hindi nagawa ang user.',

    // ── Create Folder Modal ──
    parentFolder: 'Parent Folder',
    rootNoParent: 'Root (Walang parent)',
    unassigned: 'Hindi nakatalaga',
    visibility: 'Visibility',
    adminOnly: 'Admin Lamang',
    private: 'Pribado',

    // ── Document Card ──
    review: 'Suriin',
    archive: 'I-archive',
    requestDeleteOption: 'Humiling ng Pagtanggal',
    by: 'ni ',

    // ── File Preview ──
    noDocumentSelected: 'Walang napiling dokumento.',
    previewNotAvailableFor: 'Hindi magamit ang preview para sa',
    files: 'mga file.',
    loadingPreview: 'Naglo-load ng preview...',
    browserNoVideo: 'Hindi sinusuportahan ng iyong browser ang pag-playback ng video.',
    downloadToPreview: 'I-download para Makita',
    downloadFile: 'I-download ang File',
    previewNotAvailable: 'Hindi magamit ang preview.',

    // ── Folder Tree ──
    searchFolders: 'Maghanap ng mga folder...',

    // ── Activity Log Export Popup ──
    activityLogAlert: 'Alerto ng Activity Log',
    activityLogsReached: 'Ang activity logs ay umabot na sa',
    records: 'mga tala.',
    downloadExcelReport: 'Mangyaring i-download ang Excel report.',
    exportedLogsArchived: 'Ang mga na-export na log ay ililipat sa archive pagkatapos i-download.',
    dismiss: 'I-dismiss',
    downloading: 'Dina-download...',
    pdf: 'PDF',
    excel: 'Excel',

    // ── Page Titles (used in Header) ──
    pageTitles: {
      dashboard: 'Dashboard',
      documents: 'Pamamahala ng Dokumento',
      scanner: 'Scanner Dashboard',
      users: 'Pamamahala ng User',
      folders: 'Pamamahala ng Folder',
      departments: 'Pamamahala ng Departamento',
      archive: 'Archive',
      trash: 'Trash',
      'activity-log': 'Activity Log',
      approvals: 'Mga Pending na Pag-apruba',
      'admin-delete-requests': 'Kahilingan ng Pagtanggal',
      profile: 'Aking Profile',
      settings: 'Mga Setting'
    }
  }
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

function getFromPath(obj: any, path: string) {
  return path.split('.').reduce((acc: any, p: string) => (acc ? acc[p] : undefined), obj);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const stored = localStorage.getItem(LANG_KEY) || 'English (US)';
    if (stored === 'Tagalog') return 'tl';
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem(LANG_KEY, lang === 'tl' ? 'Tagalog' : 'English (US)');
  }, [lang]);

  const setLang = (l: LangCode) => setLangState(l);

  const t = (key: string) => {
    const v = getFromPath(resources[lang], key);
    if (v === undefined) return key;
    return String(v);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
